name: Main

# name: Release

# on:
#   pull_request:
#     types:
#       - closed
#     branches:
#       - master

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install bump2version
        run: pip install bump2version

      - name: Run bump2version
        run: bump2version patch --new-version 1.0.0 # Adjust version bump as needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
