name: release

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Release
      run: |
        # Your release script or commands go here

# Changelog configuration
changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Features 
      labels:
        - feature
    - title: Bug fixes 
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
