name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - master


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Create Release
        id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') ? github.ref : '' }}"

      - name: Get the Release ID
        run: echo "Release ID - ${{ steps.create_release.outputs.id }}"
